logging:
  level:
    root: DEBUG
server:
  error:
    whitelabel:
      enabled: true
  port: 1997
spring:
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 1200000
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: data-source
    url: jdbc:mysql://localhost:3306/handmadecards?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    password: root
    username: root
  jackson:
    date-format: MMMM dd yyyy / HH:mm
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    host_address: host_address
    username: username
    password: password
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    protocol: smtp



security:
  public-pattern: /api/public/**
  auth:
    username: user_name
    url: http://localhost:8081/oauth/check_token
    client_id: test
    client_password: twinkle_heart
    connection_timeout: 60
    read_timeout: 60
    whitelist: >
      /,
      /v2/api-docs,
      /swagger-resources,
      /swagger-resources/**,
      /configuration/ui,
      /configuration/security,
      /swagger-ui.html,
      /webjars/**,
      /api/public/**

swagger:
  host:
    address: localhost:1997
    path: /
  api:
    name: E-commerce Api Documentation
    version: v1
  contact:
    name: Kathee
    url: https://www.linkedin.com/in/katheesan/
    email: kkatheesan@gmail.com

